spring:
  config:
    activate:
      on-profile: bert

app:
  indexer:
    default: bert
  search:
    default: bert
  parser.ocr:
    tesseract:
      dataPath: /usr/share/tessdata
  embeddings:
    store:
      default: hashmap
