spring:
  config:
    activate:
      on-profile: lucene-vector

app:
  indexer:
    default: lucene-vector
  search:
    default: lucene-vector
  parser.ocr:
    tesseract:
      dataPath: /usr/share/tessdata
