-- Script d'initialisation de la base H2

CREATE TABLE IF NOT EXISTS document_metadata (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titre_document VARCHAR(500) NOT NULL,
    auteur_depot VARCHAR(255) NOT NULL,
    categories_ens VARCHAR(100) NOT NULL,
    depot_date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nom_fichier VARCHAR(500),
    taille_fichier BIGINT,
    ocr_index_done BOOLEAN DEFAULT FALSE NOT NULL
);

-- Index
CREATE INDEX idx_depot_date ON document_metadata(depot_date_time DESC);
CREATE INDEX idx_categorie ON document_metadata(categories_ens);
CREATE INDEX idx_auteur ON document_metadata(auteur_depot);

-- Commentaires
COMMENT ON COLUMN document_metadata.titre_document IS 'Titre du document fourni par l''utilisateur';
COMMENT ON COLUMN document_metadata.auteur_depot IS 'Nom de la personne ayant dÃ©posÃ© le document';
COMMENT ON COLUMN document_metadata.categories_ens IS 'Type de document (RAPPORT, FACTURE, CONTRAT, NOTE)';
COMMENT ON COLUMN document_metadata.depot_date_time IS 'Date et heure du dÃ©pÃ´t du document';
COMMENT ON COLUMN document_metadata.nom_fichier IS 'Nom du fichier original';
COMMENT ON COLUMN document_metadata.taille_fichier IS 'Taille du fichier en octets';
COMMENT ON COLUMN document_metadata.ocr_index_done IS 'OCR index processed for this document';

CREATE TABLE lucene_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_name VARCHAR(255) NOT NULL,
    index_data BLOB,
    last_updated TIMESTAMP,
    document_count BIGINT,
    CONSTRAINT uk_lucene_index_name UNIQUE (index_name)
);

