-- Script d'initialisation de la base PostgreSQL

CREATE TABLE IF NOT EXISTS document_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre_document VARCHAR(500) NOT NULL,
    auteur_depot VARCHAR(255) NOT NULL,
    categories_ens VARCHAR(100) NOT NULL,
    depot_date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nom_fichier VARCHAR(500),
    taille_fichier BIGINT,
    ocr_index_done BOOLEAN DEFAULT FALSE NOT NULL
);

-- Index
CREATE INDEX IF NOT EXISTS idx_depot_date ON document_metadata(depot_date_time DESC);
CREATE INDEX IF NOT EXISTS idx_categorie ON document_metadata(categories_ens);
CREATE INDEX IF NOT EXISTS idx_auteur ON document_metadata(auteur_depot);

-- Commentaires
COMMENT ON COLUMN document_metadata.titre_document IS 'Titre du document fourni par l''utilisateur';
COMMENT ON COLUMN document_metadata.auteur_depot IS 'Nom de la personne ayant depose le document';
COMMENT ON COLUMN document_metadata.categories_ens IS 'Type de document (RAPPORT, FACTURE, CONTRAT, NOTE)';
COMMENT ON COLUMN document_metadata.depot_date_time IS 'Date et heure du depot du document';
COMMENT ON COLUMN document_metadata.nom_fichier IS 'Nom du fichier original';
COMMENT ON COLUMN document_metadata.taille_fichier IS 'Taille du fichier en octets';
COMMENT ON COLUMN document_metadata.ocr_index_done IS 'OCR index processed for this document';

CREATE TABLE IF NOT EXISTS lucene_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_name VARCHAR(255) NOT NULL,
    index_data BYTEA,
    last_updated TIMESTAMP,
    document_count BIGINT,
    CONSTRAINT uk_lucene_index_name UNIQUE (index_name)
);

CREATE TABLE IF NOT EXISTS bert_embeddings_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_name VARCHAR(255) NOT NULL,
    index_data BYTEA,
    last_updated TIMESTAMP,
    document_count BIGINT,
    CONSTRAINT uk_bert_embeddings_index_name UNIQUE (index_name)
);

CREATE TABLE IF NOT EXISTS lucene_vector_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_name VARCHAR(255) NOT NULL,
    index_data BYTEA,
    last_updated TIMESTAMP,
    document_count BIGINT,
    CONSTRAINT uk_lucene_vector_index_name UNIQUE (index_name)
);

CREATE TABLE IF NOT EXISTS document_embedding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    chunk_index INTEGER NOT NULL DEFAULT 0,
    chunk_count INTEGER NOT NULL DEFAULT 1,
    title VARCHAR(1000) NOT NULL,
    author VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    filename VARCHAR(1000) NOT NULL,
    depot_datetime TIMESTAMP,
    content_text TEXT,
    embedding_data BYTEA NOT NULL,
    -- Un document peut avoir plusieurs chunks: l'unicite porte sur (document_id, chunk_index).
    CONSTRAINT uk_document_embedding_doc_chunk UNIQUE (document_id, chunk_index)
);

